act_mdn: relu
cls:
  cls_dataset: /data103/makinen/des_results/cls_net/cls_train_test_sys.npz
  cls_normalisation_stats_filename: /data103/makinen/des_results/cls_net/cls_statistics_for_normalisation.npz
  cut_idx: 22
  epochs: 300
  hidden_size: 256
  n_components: 4
  n_hidden_mdn: 100
  n_layers: 10
  n_layers_mdn: 1
  net_dir: cls_net
  w_filename: w_cls_compress.pkl
filters:
- 1
- 1
- 1
gradient_clip: 1.0
max_iterations: 7000
min_iterations: 200
model_key: 44
mpk_input_filters:
- 4
- 6
mpk_kernel: 5
mpk_strides:
- 1
- 1
n_components: 4
n_hidden_mdn: 100
n_layers_mdn: 1
n_params: 3
n_summaries:
  A: 4
  B: 4
  C: 4
  cls: 10
network_code_dir: /home/makinen/repositories/des-hybrid/
patch_net:
  act_cnn: relu
  act_dense: smooth_leaky
  batch_size: 128
  do_noise_val: 0
  epochs: 1
  learning_rate: 1.0e-05
  model_type: default
  n_components: 4
  n_extra: 4
  n_filters: 32
  n_hidden_mdn: 100
  n_layers_mdn: 1
  network_type: cnn
  noise_amp: 0.001
  patience: 20
  w_filename: w_patch_
patch_net_w_dir: /data103/makinen/des_results/patch_nets/
patch_w_filename: w_cls_compress_default.pkl
patience: 20
polynomial_degrees:
- 0
- 1
- 2
project_dir: /data103/makinen/des_results/dry_single/
run_name: vanilla
single_param: 1
summary_path: /data103/makinen/des_results/dry_single/summaries_
theta_star:
- 0.3
- 0.8
- -1.0
